project :
        artifactId:content-repository
        name:cep
        version:0.0.1
        description:flexible content repository

info:
         artifact : content-repository
         name : cep
         description : REST content repository
         version : 0.0.1
         
spring:
         profiles :
                   active: dev
                           
simple :
         name : przodownik
         age : 35
         disabled : true
         
                                  